name: json_convert
description: Generate codes for freezed, json_serializable, classic models easily
version: 1.0.0
homepage: "https://github.com/babakcode/json_convert"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  recase: ^4.1.0
  args: ^2.4.2
  path: ^1.8.3
  process_run: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

